zammad-nginx:
    environment:
      VIRTUAL_HOST: ${VHOST:-support.domain.tld}
      LETSENCRYPT_HOST: ${LE_HOST:-support.domain.tld}
    <<: *zammad-service
    command: ["zammad-nginx"]
    expose:
      - "${NGINX_PORT:-8080}"
    ports:
      - "${NGINX_EXPOSE_PORT:-8080}:${NGINX_PORT:-8080}"
    depends_on:
      - zammad-railsserver
